# arg 1:  the new package version
# arg 2:  the old package version

KERNEL_NAME=-odroid-xu4
KERNEL_VERSION=6.1.0-rc6

post_install () {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}

post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}

post_remove() {
  rm -f boot/initramfs-linux.img
}
