# arg 1:  the new package version
# arg 2:  the old package version

KERNEL_NAME=-odroid-xu3
KERNEL_VERSION=5.15.7-0-0-0-0-0-0-0-0-1-1-2-2-2-3-3

post_install () {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}

post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}

post_remove() {
  rm -f boot/initramfs-linux.img
}
